//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToilluminateModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileTypeMaster
    {
        public int FileTypeID { get; set; }
        public string FileTypeName { get; set; }
        public string FileTypeFormat { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    }
}
