//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToilluminateModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ToilluminateEntities : DbContext
    {
        public ToilluminateEntities()
            : base("name=ToilluminateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GroupMaster> GroupMaster { get; set; }
        public virtual DbSet<PlayerMaster> PlayerMaster { get; set; }
        public virtual DbSet<PlayerPlayListLinkTable> PlayerPlayListLinkTable { get; set; }
        public virtual DbSet<PlayListMaster> PlayListMaster { get; set; }
        public virtual DbSet<TemplatTypeMaster> TemplatTypeMaster { get; set; }
        public virtual DbSet<TempleFileLinkTable> TempleFileLinkTable { get; set; }
        public virtual DbSet<TempletMaster> TempletMaster { get; set; }
        public virtual DbSet<UserMaster> UserMaster { get; set; }
        public virtual DbSet<FileMaster> FileMaster { get; set; }
        public virtual DbSet<FolderMaster> FolderMaster { get; set; }
    }
}
