//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToilluminateClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempleFileLinkTable
    {
        public int ID { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<int> TempletID { get; set; }
        public Nullable<int> FileID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    }
}
